name: Python CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # No requirements file present, but you can add one later

      - name: Check Python syntax
        run: python -m py_compile main.py

      - name: Run server (basic smoke test)
        run: |
          python main.py &
          sleep 3
          # You could add curl tests here if desired
